### ISSUE TITLE
Error Header Amadeus with cakephp

### ISSUE THREAD

**Issue by henriqu3** [sunspikes/php-amadeus#11]
I'm Brazilian and i work with amadeus.

The problem is, i'm trying use pnr_cancel, that needs a pnr has been retrieved.
But, the following error appears:

17 | Session | no agreement on destination.

And my code is that:

My action in controller is:

`public function deletePnr($pnr) {  
        $ws = new Client(**DIR** . DS . '..' . DS . 'wsdl' . DS . '1ASIWIOPIEM_PDT_20140828_132845.wsdl', false);

```
    $ws->securityAuthenticate('xxxxx', 'xxxxx', 'xxxxx=', x, 'xxxxxx');                
    $ws->pnrRetrieve($pnr);                        
    $ws->pnrCancel();        
    $ws->securitySignout();                                          
}`
```

and my methods in Lib is:

`public function pnrRetrieve($pnr_id)
    {
        $params = array();
        $params['PNR_Retrieve']['retrievalFacts']['retrieve']['type'] = 2;
        $params['PNR_Retrieve']['retrievalFacts']['reservationOrProfileIdentifier']['reservation']['controlNumber'] = $pnr_id;

```
    //die(print_r($params));

    $this->_data = $this->_client->__soapCall('PNR_Retrieve', $params, null,
        $this->getHeaderSession(), $this->_headers);

    $this->debugDump($params, $this->_data);
}

public function pnrCancel(){
    //die($pnr_id);
    $params = array();         
    $params['PNR_Cancel']['pnrActions']['optionCode'] = 11;        
    $params['PNR_Cancel']['cancelElements']['entryType'] = 'I';  
    //$params['PNR_Cancel']['reservationInfo']['reservation']['controlNumber'] = $pnr_id;         

    $this->_data = $this->_client->__soapCall('PNR_Cancel', $params, null,
        $this->getHeaderSession(), $this->_headers);

    $this->debugDump($params, $this->_data);
}`
```

PS: I'm using cakephp 2x

**Comment by DerMika** [comment]
Hi, **'17 | Session | no agreement on destination.'**  usually occurs because the message you are trying to call is not activated on your WSDL. 

Are you sure you have the PNR_Cancel message activated on the WSAP your received? You can check to see if this message is in the WSDL file you received from Amadeus.

**Comment by henriqu3** [comment]
Omg, i dont believe someone has helped me.
So, i call the xsd pnr_cancel in wsdl, but the file wspa i dont know..

Enviado do meu iPhone

**Comment by DerMika** [comment]
There can be other reasons for this error, I think you'd better contact your Amadeus support and have them investigate what you're doing wrong. If you have applied with Amadeus for a project, you should have been assigned contact person to support you during development. You should be able to ask this question to your support contact.

WSAP = Web Service Access Point -> your personal access to the Amadeus Web Services for the application you are developing. 

If you do not have the PNR_Cancel message activated in your WSDL, you can ask Amadeus to activate it and then you'll receive a new WSDL with this message - on your WSAP.

**Comment by henriqu3** [comment]
I got it, but imyou thit that the way i calling the pnr_cancel ia wrong?
Is very difficult talk with them..
When i get home i'll check this on wsdl, but can't i call pnr_cancel on wsdl?
Other question, may be, my permissions on account can do this happens?

Enviado do meu iPhone

**Comment by DerMika** [comment]
If you get "no agreement on destination", the problem is probably in the WSDL setup and not (yet) in the content of the message you are sending. 

When you request access to the Amadeus Web Services, you have to tell Amadeus which messages you want to call. 

You will then receive a WSDL file with all the messages you requested in them. If you need any more additional messages later on, you will have to request a new WSDL from Amadeus with the new messages included. If you try to call any messages from the Amadeus Web Services that you did not request access to, you'll get the error "no agreement on destination".

According to my documentation, this is the call you should send out if you want to cancel the entire itinerary on a PNR in context:

    <PNR_Cancel>
        <pnrActions>
            <optionCode>0</optionCode>
        </pnrActions>
        <cancelElements>
            <entryType>I</entryType>
        </cancelElements>
    </PNR_Cancel>

**Comment by henriqu3** [comment]
Other thing, this function is called after or inside pnr_ retrieve?

Enviado do meu iPhone

**Comment by DerMika** [comment]
First you call PNR_Retrieve (and you use an optionCode which keeps the PNR open like 0 for example) and then you call PNR_Cancel.

**Comment by henriqu3** [comment]
Alright, i think it will helps me a lot.
Man, thanks a lot.
Another question can i send email to you?
Because the amadeus support is poor, when you are from brazil.
Sorry for my poor english.
See ya!

Enviado do meu iPhone

**Comment by DerMika** [comment]
Well, sure you can, but I can't promise anything!

**Comment by henriqu3** [comment]
For sure, i undertand you.
But, every help is a help!!!

Enviado do meu iPhone

**Comment by DerMika** [comment]
Hey @henriqu3 in the mean time, I've built my own Amadeus Web Service client which supports many more messages than this one does. Maybe it can be useful to you too. See https://github.com/amabnl/amadeus-ws-client
